title: The only Chief Meteorologist
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://keenness25.github.io/Just_the_Docs

aux_links:
  Template Repository: https://github.com/keenness25/Just_the_Docs
